// importieren der erforderlichen module
import Head from 'next/head';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';

// erstellen der funktion
export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  const [tempInCelsius, setTempInCelsius] = useState('');

// abrufen der wetterdaten
  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);


    const MY_WEATHER_API_KEY = 'fed239da384834b437c17b4e27c0fe22';
    const apiUrl = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${MY_WEATHER_API_KEY}`;

    axios
      .get(apiUrl)
      .then((response) => {
        setWeather(response.data);
        const weatherData = response.data;
        const tempCelsius = (weatherData.main.temp - 273.15).toFixed(2);
        setTempInCelsius(tempCelsius);
      })
      .catch((error) => {
        console.error(error);
      })
      .finally(() => {
        setLoading(false);
      });
  };

// Aufbau der Webseite
  return (
    <div className="container">
  <Head>
    <title>weather-app</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico"/>
  </Head>
  <div className="header">
    <h1>weather</h1>
  </div>
  <div>
    <form onSubmit={fetchWeather}>
      <input
        type="text"
        placeholder="enter city"
        value={city}
        onChange={(e) => setCity(e.target.value)}
      />
      <button type="submit">
        <BsSearch />
      </button>
    </form>
  </div>

  {loading && <p>Loading...</p>}
  {weather.main && (
    <div className="weatherInfo">
      <h2>weather in {weather.name}, {weather.sys.country}</h2>
      <p>temperature: {tempInCelsius}°C</p>
      <p>humidity: {weather.main.humidity}%</p>
      <p>cloud formation: {weather.weather[0].description}</p>
    </div>
  )}
</div>
  );
}